### ISSUE TITLE
Change button 'state' by code!

### ISSUE THREAD

**Issue by Cleversou1983** [swifty-iOS/RadioCheckboxButton#2]
Hi there, I absolutely love this lib... But I'm not having success changing the state of a radio/checkbox by code. The app I'm developing have a form, and when the field is already filled in model and user goest to de update screen, the button must be on state 'selected'... How can I achieve this? Thanks a lot!

**Comment by Cleversou1983** [comment]
Oh, looking at the code I've come to the property isOn... Thanks!!!

**Comment by manishbhande** [comment]
Hope you have found the property. Thanks for using this lib.
