### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by jassimkm** [swifty-iOS/RadioCheckboxButton#5]
Any Quick fix for RTL Support

**Comment by manishbhande** [comment]
Sorry for the late reply. Will fix this soon.

**Comment by zaidqattan** [comment]
same issue here, please can you support RTL ? @manishbhande

**Comment by zaidqattan** [comment]
@jassimkm 

this is a quick fix:

func revertRadioButton(_ btn: RadioButton){
    btn.transform = CGAffineTransform(scaleX: -1.0, y: 1.0)
    btn.titleLabel?.transform = CGAffineTransform(scaleX: -1.0, y: 1.0)
    btn.imageView?.transform = CGAffineTransform(scaleX: -1.0, y: 1.0)
}

**Comment by manishbhande** [comment]
Please use above solution.
