### ISSUE TITLE
it does not respect app direction ( LTR & RTL )

### ISSUE THREAD

**Issue by alauthor** [swifty-iOS/RadioCheckboxButton#6]

**Comment by manishbhande** [comment]
sorry for the late reply.
Please refer https://github.com/swifty-iOS/RadioCheckboxButton/issues/5

**Comment by alauthor** [comment]
no problem but when I use the #5 solve it looks wierd too 
I think you should update the view direction not just position because the right image it still looks wierd after using #5 solution .

**Comment by manishbhande** [comment]
Ohh. I really appreciate your comments. I will fix it soon.

**Comment by alauthor** [comment]
Okay, Im looking forward to hear from you .
